---
AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket for Lambda Packages

Parameters:
  TagServiceName:
    AllowedValues:
      - moppa development
    Default: moppa development
    Description: Name of service associated with this stack
    Type: String
  TagServiceCode:
    AllowedValues:
      - ZZBGCS
    Default: ZZBGCS
    Description: Code for tracking resource usage by the associated service
    Type: String
  TagEnvironment:
    Default: dev
    Description: Type of project resource
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
      - Key: ServiceName
        Value: !Ref TagServiceName
      - Key: ServiceCode
        Value: !Ref TagServiceCode
      - Key: Environment
        Value: !Ref TagEnvironment

Outputs:
  StackBucket:
    Description: Bucket created by this stack for hosting lambda source
    Value: !Ref Bucket
    Export:
      Name: !Sub "${TagEnvironment}-${AWS::StackName}"
